export class PermissionConstants {
  public static readonly ViewManageUser = "ViewManageUser";
  public static readonly CreateBooking = "CreateBooking";
  public static readonly ViewQueryDOStatus = "ViewQueryDOStatus";
  public static readonly ViewQueryDO = "ViewQueryDO";
  public static readonly ViewQueryBookingForForwarder = "ViewQueryBookingForForwarder";
  public static readonly ViewQueryBookingForShipping = "ViewQueryBookingForShipping";
  public static readonly ViewAssignPickTask = "ViewAssignPickTask";
  public static readonly BtnAssignPickTaskAssign = "BtnAssignPickTaskAssign";
  public static readonly CancelBooking = "CancelBooking";
  public static readonly EditBookingFormUpdatedTotalGrosswgt = "EditBookingFormUpdatedTotalGrosswgt"; // 毛重
  public static readonly EditBookingFormUpdatedTotalCaseCnt = "EditBookingFormUpdatedTotalCaseCnt"; // 箱數
  public static readonly EditBookingFormUpdatedTotalVolumeWeight = "EditBookingFormUpdatedTotalVolumeWeight"; // 材積
  public static readonly EditBookingFormExpressTerm = "EditBookingFormExpressTerm" //快遞物流送達條件
  // public static readonly BtnBookingSearchForForwarder = "BtnBooki ngSearchForForwarder";
  // public static readonly BtnDocumentDownloadUploadForForwarder = "BtnDocumentDownloadUploadForForwarder";
  public static readonly BtnUrgentFlag = "BtnUrgentFlag"; // 運輸急單註記
  public static readonly BtnRedelivery = "BtnRedelivery"; // 重送註記
  public static readonly BtnRewarehouse = "BtnRewarehouse"; // 預計回倉註記
  public static readonly BtnDeleteBookingDetail = "BtnDeleteBookingDetail"; // 刪除
  public static readonly BtnAssignmentDistrictMaintain = "BtnAssignmentDistrictMaintain"; // 出貨單查詢 功能 棒棒糖

  public static readonly ViewDOInvoiceReport = "ViewDOInvoiceReport";
  public static readonly ViewConsignmentDailyReport = "ViewConsignmentDailyReport";

  public static readonly ViewAddressMaintainSetting = "ViewAddressMaintainSetting";
  public static readonly EditAddressMaintainSetting = "EditAddressMaintainSetting";
  public static readonly ViewFlowDoorlaneSearch = "ViewFlowDoorlaneSearch";
  public static readonly ViewWarehouseCalendar = "ViewWarehouseCalendar";
  public static readonly EditWarehouseCalendar = "EditWarehouseCalendar";
  public static readonly ViewLeaveWarehouse = "ViewLeaveWarehouse";
  public static readonly BtnContianerUnLock = "BtnContianerUnLock";
  public static readonly ChangeBookingDetailStatus = "ChangeBookingDetailStatus"
  public static readonly BtnContianerLock = "BtnContianerLock";
  public static readonly ViewWarehousingCreation = "ViewWarehousingCreation";
  public static readonly ViewWarehousingSearch = "ViewWarehousingSearch";
  public static readonly ViewRFQSetting = "ViewRFQSetting";
  public static readonly ViewUploadDocReport = "ViewUploadDocReport";
  public static readonly ViewCustomsDeclarationReport = "ViewCustomsDeclarationReport";
  public static readonly ViewFreightAnalysisReport = "ViewFreightAnalysisReport";
  public static readonly ViewPaymentReportForDHL = "ViewPaymentReportForDHL";
  public static readonly CreateRFQ = "CreateRFQ";
  public static readonly BtnRFQApply = "BtnRFQApply";
  public static readonly BtnRFQRecall = "BtnRFQRecall";
  public static readonly BtnRFQDelete = "BtnRFQDelete";
  public static readonly BtnRFQApproved = "BtnRFQApproved";
  public static readonly BtnRFQInvalid = "BtnRFQInvalid";
  public static readonly ViewTariffRateSetting = "ViewTariffRateSetting";
  public static readonly ViewAirwaysExpenseSetting = "ViewAirwaysExpenseSetting";
  public static readonly BatchUpdatedDeclarationBookingInfo = "BatchUpdatedDeclarationBookingInfo";
  public static readonly ViewImportDeclaration = "ViewImportDeclaration";
  public static readonly BtnAirwaysExpenseApply = "BtnAirwaysExpenseApply";
  public static readonly BtnAirwaysExpenseRecall = "BtnAirwaysExpenseRecall";
  public static readonly BtnAirwaysExpenseDelete = "BtnAirwaysExpenseDelete";
  public static readonly BtnAirwaysExpenseApproved = "BtnAirwaysExpenseApproved";
  public static readonly BtnAirwaysExpenseInvalid = "BtnAirwaysExpenseInvalid";
  public static readonly CreateAirwaysExpense = "CreateAirwaysExpense";
  public static readonly ViewShipImportConfirmReport = "ViewShipImportConfirmReport";
  public static readonly ViewShipImportConfirmReportForBooking = "ViewShipImportConfirmReportForBooking";
  public static readonly ViewShipImportConfirmReportForWarehousing = "ViewShipImportConfirmReportForWarehousing";
  public static readonly ViewPaymentErrorReport = "ViewPaymentErrorReport";
  public static readonly ViewPaymentReport = "ViewPaymentReport";

  public static readonly ViewNonGUICheck = "ViewNonGUICheck";
  public static readonly EditNonGUICheck = "EditNonGUICheck";
  public static readonly ViewGUICheck = "ViewGUICheck";
  public static readonly EditGUICheck = "EditGUICheck";
  public static readonly EditDetailGUICheck = "EditDetailGUICheck";
  public static readonly ViewImportDeclarationFeeAccountingReport = "ViewImportDeclarationFeeAccountingReport";
  public static readonly ViewImportDeclarationFeeReport = "ViewImportDeclarationFeeReport";
  public static readonly ViewBilling = "ViewBilling";
  public static readonly EditBilling = "EditBilling";
  public static readonly BillingDownload = "BillingDownload";
  public static readonly BillingUpload = "BillingUpload";
  public static readonly NonGovermentUniformInvoiceDownload = "NonGovermentUniformInvoiceDownload";
  public static readonly NonGovermentUniformInvoiceUploadownload = "NonGovermentUniformInvoiceUploadownload";
  public static readonly GovermentUniformInvoiceDownload = "GovermentUniformInvoiceDownload";
  public static readonly GovermentUniformInvoiceDownloadPDF = "GovermentUniformInvoiceDownloadPDF";

  public static readonly ViewDOAbnormal = "ViewDOAbnormal";
  public static readonly DOAbnormalEdit = "DOAbnormalEdit";
  public static readonly DOAbnormalUpload = "DOAbnormalUpload";
  public static readonly DOAbnormalSendNotification = "DOAbnormalSendNotification";
  public static readonly DOAbnormalReplyNotification = "DOAbnormalReplyNotification";

  public static readonly ViewRequestExpenseReport = "ViewRequestExpenseReport";
  public static readonly UpdateRmbPrice = "UpdateRmbPrice";
  public static readonly DownloadRmbPriceReport = "DownloadRmbPriceReport";
  public static readonly CreateDeclarationBooking = "CreateDeclarationBooking";
  public static readonly ViewInOutWarehousingSearch = "ViewInOutWarehousingSearch";
  public static readonly ViewMergeKeySearch = "ViewMergeKeySearch";
  public static readonly BtnMergeKeyCSRWithdraw = "BtnMergeKeyCSRWithdraw";
  public static readonly BtnMergeKeyShippingCancel = "BtnMergeKeyShippingCancel";

  public static readonly ViewReceivingInstruction = "ViewReceivingInstruction";
  public static readonly EditReceivingInstruction = "EditReceivingInstruction";
  public static readonly ViewFacilityAnnouncement = "ViewFacilityAnnouncement";
  public static readonly FacilityAnnouncementAdmin = "FacilityAnnouncementAdmin";
  public static readonly ViewAdvisingAbnormal = "ViewAdvisingAbnormal";
  public static readonly AdvisingAbnormalEdit = "AdvisingAbnormalEdit";
  public static readonly AdvisingAbnormalUpload = "AdvisingAbnormalUpload"
  public static readonly AdvisingAbnormalSendNotification = 'AdvisingAbnormalSendNotification';
  public static readonly AdvisingAbnormalReplyNotification = 'AdvisingAbnormalReplyNotification';
  public static readonly ViewLaaSCalender = "ViewLaaSCalender";
  public static readonly EditLaaSCalender = "EditLaaSCalender";
  public static readonly ViewQueryADStatus = "ViewQueryADStatus";
  public static readonly ViewFaqMaintenance = "ViewFaqMaintenance";
  public static readonly ViewFAQSearch = "ViewFAQSearch";
  public static readonly ViewForwarderCooperation = 'ViewForwarderCooperation';
  public static readonly ViewCustomerChopSignSample = "ViewCustomerChopSignSample";

  public static readonly BtnWarehousingPrint = "BtnWarehousingPrint";
  public static readonly BtnWarehousingImportAD = "BtnWarehousingImportAD";
  public static readonly BtnWarehousingImportDropshipment = "BtnWarehousingImportDropshipment";
  public static readonly BtnBillingDisplay = "BtnBillingDisplay";
  public static readonly BtnWarehousingAssign = "BtnWarehousingAssign";
  public static readonly BtnWarehousingCopy = "BtnWarehousingCopy";
  public static readonly BtnWarehousingUpload = "BtnWarehousingUpload";
  public static readonly BtnWarehousingQuotation = "BtnWarehousingQuotation";
  public static readonly EditWarehousingFormExpressTerm = "EditWarehousingFormExpressTerm";
  public static readonly EditBookingDetailSerialPda = "EditBookingDetailSerialPda";
  public static readonly BtnExpenseView = "BtnExpenseView";
  public static readonly BtnExpenseApply = "BtnExpenseApply";
  public static readonly BtnApproveNonGUI = "BtnApproveNonGUI";
  public static readonly EditRFQRemark = "EditRFQRemark";
  public static readonly BtnApproveGUI = "BtnApproveGUI";
  public static readonly ViewSubscription = "ViewSubscription";
  public static readonly ViewFreightSearch = "ViewFreightSearch";
  public static readonly CancelWarehousing = "CancelWarehousing";
  public static readonly EditWarehousingRelatedBilling = 'EditWarehousingRelatedBilling';
  public static readonly EditBookingRelatedBilling = 'EditBookingRelatedBilling';
  public static readonly ViewUserGroupSubscription = "ViewUserGroupSubscription";
  public static readonly EditUserGroupSubscription = "EditUserGroupSubscription";
  public static readonly ViewAutoPrintSetting = "ViewAutoPrintSetting";
  public static readonly EditAutoPrintSetting = "EditAutoPrintSetting";
  public static readonly ViewTenantMappingUserGroupDetailDialog = "ViewTenantMappingUserGroupDetailDialog";
  public static readonly ViewIntransitUpdate = "ViewIntransitUpdate";
}
